# Generated by Django 4.2.3 on 2025-02-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('actions', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('actions_date', models.DateTimeField(verbose_name='action date')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websrv.summary')),
            ],
        ),
    ]
