# Generated by Django 4.2.3 on 2025-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='expertise_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
