# Generated by Django 4.2.3 on 2025-04-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0002_cosponsor_bill_cosponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosponsor',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
