# Generated by Django 4.2.3 on 2025-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0003_bill_bill_number_bill_bill_type_bill_congress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='actions',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
