# Generated by Django 4.2.3 on 2025-04-16 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0004_billview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timnestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likee', to='websrv.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='websrv.user')),
            ],
            options={
                'ordering': ['-timnestamp'],
                'unique_together': {('user', 'bill')},
            },
        ),
    ]
