# Generated by Django 4.2.3 on 2025-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0004_alter_bill_actions_alter_bill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='actions_date',
            field=models.DateField(verbose_name='action date'),
        ),
    ]
