# Generated by Django 4.2.3 on 2025-02-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0006_bill_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
