# Generated by Django 4.2.3 on 2025-05-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='expertise_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='websrv.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
