# Generated by Django 4.2.3 on 2025-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0007_comment_expertise_tags_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='websrv.user'),
        ),
    ]
