# Generated by Django 4.2.3 on 2025-03-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0008_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
