# Generated by Django 4.2.3 on 2025-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0008_user_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_reps',
            field=models.ManyToManyField(related_name='followers', to='websrv.cosponsor'),
        ),
    ]
