# Generated by Django 4.2.3 on 2025-04-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='websrv.user'),
        ),
    ]
