# Generated by Django 4.2.3 on 2025-02-15 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0002_text_bill_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='congress',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websrv.summary'),
        ),
    ]
