# Generated by Django 4.2.3 on 2025-02-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0005_alter_bill_actions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
