# Generated by Django 4.2.3 on 2025-02-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0006_bill_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='url',
        ),
    ]
