# Generated by Django 4.2.3 on 2025-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0007_remove_bill_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
