# Generated by Django 4.2.3 on 2025-04-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websrv', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='password',
            new_name='auth0_id',
        ),
    ]
